<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Configurations>Debug;Release;Stage</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mjml.Net" Version="4.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiService.Abstraction\ApiService.Abstraction.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\EmailService.Abstraction\EmailService.Abstraction.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>

</Project>
