<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Configurations>Debug;Release;Stage</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiService\ApiService.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\DataBase.Context\DataBase.Context.csproj" />
    <ProjectReference Include="..\DataBase.Repository\DataBase.Repository.csproj" />
    <ProjectReference Include="..\PagePingerHostService\PagePingerHostService.csproj" />
    <ProjectReference Include="..\OrderCleanerHostService\OrderCleanerHostService.csproj" />
    <ProjectReference Include="..\SiteMapHostService\SiteMapHostService.csproj" />
    <ProjectReference Include="..\EmailService\EmailService.csproj" />
    <ProjectReference Include="..\ImageService\ImageService.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>

</Project>
